---
version: "2"
plugins:
  eslint:
    enabled: true
    channel: eslint-4
    checks:
      import/no-unresolved:
        enabled: false
exclude_patterns:
  - ".tmp_rules/"
  - "node_modules/"
  - "test/"
